
import sympy as sp
from IPython.display import Math, display

# 変数を定義
(x_euler[0],x_euler[1],x_euler[2],x_euler[3],x_euler[4],x_euler[5]) = sp.symbols("f g h i j k")

x=[10,10,20,20,20,4]

dmdf=2/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dmdg=-(2*x_euler[0] + 2*sp.cos(x_euler[4])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2
dmdh=sp.sqrt(3)*(2*x_euler[0] + 2*sp.cos(x_euler[4])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2
dmdi=0
dmdj=(2*x_euler[0] + 2*sp.cos(x_euler[4])*sp.cos(x_euler[5]))*(sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.sqrt(3)*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 - 2*sp.sin(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dmdk=-(2*x_euler[0] + 2*sp.cos(x_euler[4])*sp.cos(x_euler[5]))*sp.cos(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 - 2*sp.sin(x_euler[5])*sp.cos(x_euler[4])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dndf=0
dndg=-(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[5])*sp.cos(x_euler[4])) - sp.sin(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 + sp.sqrt(3)/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dndh=sp.sqrt(3)*(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[5])*sp.cos(x_euler[4])) - sp.sin(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 + 1/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dndi=0
dndj=(sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.sqrt(3)*sp.cos(x_euler[4]))*(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[5])*sp.cos(x_euler[4])) - sp.sin(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 + (-sp.sqrt(3)*sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dndk=-(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[5])*sp.cos(x_euler[4])) - sp.sin(x_euler[4]))*sp.cos(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)**2 + sp.sqrt(3)*sp.cos(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] - sp.sin(x_euler[4])) + sp.sin(x_euler[5])*sp.cos(x_euler[4]) + 8)
dodf=2/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)
dodg=-(2*x_euler[0] + 2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dodh=sp.sqrt(3)*(2*x_euler[0] + 2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dodi=(2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8) + (2*x_euler[0] + 2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))*(sp.sin(x_euler[3])*sp.cos(x_euler[5]) - sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + sp.sqrt(3)*sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dodj=(-sp.sqrt(3)*sp.sin(x_euler[3])*sp.sin(x_euler[4]) - sp.sin(x_euler[3])*sp.sin(x_euler[5])*sp.cos(x_euler[4]))*(2*x_euler[0] + 2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2 + 2*sp.sin(x_euler[3])*sp.cos(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)
dodk=(-2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) - 2*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8) + (-sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) + sp.sin(x_euler[5])*sp.cos(x_euler[3]))*(2*x_euler[0] + 2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dpdf=0
dpdg=-(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5])) + sp.sin(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2 + sp.sqrt(3)/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)
dpdh=sp.sqrt(3)*(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5])) + sp.sin(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2 + 1/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)
dpdi=(sp.sqrt(3)*(-sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8) + (x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5])) + sp.sin(x_euler[3])*sp.cos(x_euler[4]))*(sp.sin(x_euler[3])*sp.cos(x_euler[5]) - sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + sp.sqrt(3)*sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dpdj=(-sp.sin(x_euler[3])*sp.sin(x_euler[4]) + sp.sqrt(3)*sp.sin(x_euler[3])*sp.sin(x_euler[5])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8) + (-sp.sqrt(3)*sp.sin(x_euler[3])*sp.sin(x_euler[4]) - sp.sin(x_euler[3])*sp.sin(x_euler[5])*sp.cos(x_euler[4]))*(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5])) + sp.sin(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2
dpdk=(-sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) + sp.sin(x_euler[5])*sp.cos(x_euler[3]))*(x_euler[2] + sp.sqrt(3)*(x_euler[1] + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5])) + sp.sin(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)**2 + sp.sqrt(3)*(sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.sin(x_euler[3])*sp.cos(x_euler[4])) + sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]) + 8)
dqdf=2/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)
dqdg=-(2*x_euler[0] - 2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2
dqdh=sp.sqrt(3)*(2*x_euler[0] - 2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2
dqdi=(-2*sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8) + (2*x_euler[0] - 2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))*(sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.sqrt(3)*sp.sin(x_euler[3])*sp.cos(x_euler[4]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2
dqdj=(-sp.sqrt(3)*sp.sin(x_euler[4])*sp.cos(x_euler[3]) - sp.sin(x_euler[5])*sp.cos(x_euler[3])*sp.cos(x_euler[4]))*(2*x_euler[0] - 2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2 + 2*sp.cos(x_euler[3])*sp.cos(x_euler[4])*sp.cos(x_euler[5])/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)
dqdk=(-sp.sin(x_euler[3])*sp.sin(x_euler[5]) - sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))*(2*x_euler[0] - 2*sp.sin(x_euler[3])*sp.sin(x_euler[5]) + 2*sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2 + (-2*sp.sin(x_euler[3])*sp.cos(x_euler[5]) - 2*sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)
drdf=0
drdg=-(x_euler[2] + sp.sqrt(3)*(x_euler[1] - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2 + sp.sqrt(3)/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)
drdh=sp.sqrt(3)*(x_euler[2] + sp.sqrt(3)*(x_euler[1] - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2 + 1/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)
drdi=(sp.sqrt(3)*(-sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.cos(x_euler[3])*sp.cos(x_euler[5])) - sp.sin(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8) + (x_euler[2] + sp.sqrt(3)*(x_euler[1] - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))*(sp.sin(x_euler[3])*sp.sin(x_euler[4])*sp.sin(x_euler[5]) - sp.sqrt(3)*sp.sin(x_euler[3])*sp.cos(x_euler[4]) + sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2
drdj=(-sp.sin(x_euler[4])*sp.cos(x_euler[3]) + sp.sqrt(3)*sp.sin(x_euler[5])*sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8) + (-sp.sqrt(3)*sp.sin(x_euler[4])*sp.cos(x_euler[3]) - sp.sin(x_euler[5])*sp.cos(x_euler[3])*sp.cos(x_euler[4]))*(x_euler[2] + sp.sqrt(3)*(x_euler[1] - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2
drdk=(-sp.sin(x_euler[3])*sp.sin(x_euler[5]) - sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))*(x_euler[2] + sp.sqrt(3)*(x_euler[1] - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3])) + sp.cos(x_euler[3])*sp.cos(x_euler[4]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)**2 + sp.sqrt(3)*(sp.sin(x_euler[3])*sp.sin(x_euler[5]) + sp.sin(x_euler[4])*sp.cos(x_euler[3])*sp.cos(x_euler[5]))/(x_euler[1] - sp.sqrt(3)*(x_euler[2] + sp.cos(x_euler[3])*sp.cos(x_euler[4])) - sp.sin(x_euler[3])*sp.cos(x_euler[5]) + sp.sin(x_euler[4])*sp.sin(x_euler[5])*sp.cos(x_euler[3]) + 8)

dmdf=float(a1.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dmdg=float(a2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dmdh=float(a3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dmdi=0
dmdj=float(a5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dmdk=float(a6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dndf=0
dndg=float(b2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dndh=float(b3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dndi=0
dndj=float(b5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dndk=float(b6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodf=float(c1.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodg=float(c2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodh=float(c3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodi=float(c4.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodj=float(c5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dodk=float(c6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dpdf=0
dpdg=float(d2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dpdh=float(d3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dpdi=float(d4.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dpdj=float(d5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dpdk=float(d6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdf=float(e1.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdg=float(e2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdh=float(e3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdi=float(e4.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdj=float(e5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
dqdk=float(e6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
drdf=0
drdg=float(f2.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
drdh=float(f3.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
drdi=float(f4.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
drdj=float(f5.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))
drdk=float(f6.subs({x_euler[0]:x[0], x_euler[1]: x[1],x_euler[2]:x[2], x_euler[3]: x[3],x_euler[4]:x[4], x_euler[5]: x[5]}))


print(dmdf,dmdg,dmdh,dmdi,dmdj,dmdk,dndf,dndg,dndh,dndi,dndj,dndk,dodf,dodg,dodh,dodi,dodj,dodk,dpdf,dpdg,dpdh,dpdi,dpdj,dpdk,dqdf,dqdg,dqdh,dqdi,dqdj,dqdk,drdf,drdg,drdh,drdi,drdj,drdk)
